export default {
  endereco: 'app.neoglass.online',
  ferramentas: 'Tools',
  usuario: 'Your name',
  papel: 'NeoGlass · User',
  pedidos: {
    modulo: 'Orders',
    itens: ['Dashboard', 'Quotes', 'Orders', 'Replacements'],
    migalha: 'NeoGlass Orders › Dashboard',
    titulo: 'Orders',
    subtitulo: 'Every order · deadlines and stages',
    busca: 'Search by customer, order number…',
    filtro: 'In progress',
    fase: { ok: 'Approved', espera: 'Not approved' },
    linhas: [
      { n: '2600073', cliente: 'Central Glass Co.', vidro: 'Clear 6 mm toughened · 6 parts', fase: 'ok', prazo: 'in 9d', selo: 'on time', tom: 'ok' },
      { n: '2600072', cliente: 'North Garden site', vidro: 'Clear 6 mm toughened · 4 parts', fase: 'ok', prazo: 'in 1d', selo: 'urgent', tom: 'ok' },
      { n: '2600071', cliente: 'Aurora Builders', vidro: 'Bronze 8 mm toughened · 1 part', fase: 'ok', prazo: '8d late', selo: 'overdue', tom: 'atraso' },
      { n: '2600068', cliente: 'Valley Glazing', vidro: 'Clear 4 mm annealed · 1 part', fase: 'espera', prazo: 'no date', selo: 'awaiting approval', tom: 'espera' },
    ],
  },
  producao: {
    modulo: 'Production',
    itens: ['Board', 'Flow', 'Dispatch', 'Machines'],
    migalha: 'NeoGlass Production › Flow',
    titulo: 'Production flow',
    subtitulo: 'Every machine queue, in hours',
    unidade: 'h queued',
    gargalo: 'Bottleneck',
    folga: 'Has slack',
    maquinas: [
      { nome: 'Cutting table', fila: '6.4' },
      { nome: 'Edger', fila: '2.1' },
      { nome: 'Washer', fila: '0.8' },
      { nome: 'Tempering', fila: '3.2' },
    ],
    agora: { titulo: 'What to do now', rotulo: "Today's bottleneck", maquina: 'Cutting table' },
    margem: { titulo: 'Deadline slack', faixas: ['On pace', 'Watch', 'Blown'] },
  },
  design: {
    modulo: 'Design',
    itens: ['Projects', 'Library', '2D image', 'Hardware'],
    titulo: 'Test the opening',
    sub: 'Corner enclosure · sliding',
    dica: 'Drag to rotate the camera',
    ferragens: 'Hardware',
    cancelar: 'Cancel',
    abrir: 'Open',
  },

  corte: {
    modulo: 'Optimisation',
    itens: ['Board', 'Optimisation', 'Offcuts', 'Machines'],
    migalha: 'NeoGlass Production › Optimisation',
    titulo: 'Cut plan',
    subtitulo: 'One sheet, the whole order nested',
    chapa: 'Sheet',
    aproveitamento: 'yield',
    legenda: ['Shower door', 'Side panel', 'Shelf', 'Mirror'],
  },

  ia: {
    modulo: 'Artificial intelligence',
    itens: ['Assistant', 'Checks', 'History', 'Settings'],
    migalha: 'NeoGlass › Assistant',
    titulo: 'Assistant',
    subtitulo: 'Ask about the lite',
    voce: 'You',
    pergunta: 'Where is VG-260918-03?',
    resposta: 'Cutting table. Ships tomorrow.',
  },

  automacao: {
    modulo: 'Automation',
    itens: ['Queues', 'Rules', 'History', 'Settings'],
    migalha: 'NeoGlass › Queues',
    titulo: 'It ran by itself',
    subtitulo: 'Nobody clicked',
    feitos: [
      { nome: 'Slip sent', quando: '00:14' },
      { nome: 'Customer notified', quando: '00:14' },
      { nome: 'Stock deducted', quando: '00:15' },
    ],
  },

  visao: {
    modulo: 'Computer vision',
    itens: ['Camera', 'Openings', 'Check', 'Settings'],
    migalha: 'NeoGlass › Camera',
    titulo: 'The camera measured',
    subtitulo: 'Opening · 1800 × 1100',
    medida: '1800 × 1100',
  },

  dados: {
    modulo: 'Data',
    itens: ['Today', 'Orders', 'Margin', 'Settings'],
    migalha: 'NeoGlass › Today',
    titulo: 'Today on the floor',
    subtitulo: 'What already happened',
    numeros: [
      { n: '38', rotulo: 'on time' },
      { n: '2', rotulo: 'late' },
      { n: '41.7%', rotulo: 'margin' },
    ],
  },
}
