export default {
  endereco: 'app.neoglass.online',
  ferramentas: 'Werkzeuge',
  usuario: 'Ihr Name',
  papel: 'NeoGlass · Benutzer',
  pedidos: {
    modulo: 'Aufträge',
    itens: ['Übersicht', 'Angebote', 'Aufträge', 'Ersatzteile'],
    migalha: 'NeoGlass Aufträge › Übersicht',
    titulo: 'Aufträge',
    subtitulo: 'Alle Aufträge · Termine und Phasen',
    busca: 'Nach Kunde oder Auftragsnummer suchen…',
    filtro: 'Laufend',
    fase: { ok: 'Freigegeben', espera: 'Nicht freigegeben' },
    linhas: [
      { n: '2600073', cliente: 'Glaserei Mitte', vidro: 'Klar 6 mm ESG · 6 Teile', fase: 'ok', prazo: 'in 9 T', selo: 'im Plan', tom: 'ok' },
      { n: '2600072', cliente: 'Baustelle Nordgarten', vidro: 'Klar 6 mm ESG · 4 Teile', fase: 'ok', prazo: 'in 1 T', selo: 'dringend', tom: 'ok' },
      { n: '2600071', cliente: 'Bauunternehmen Aurora', vidro: 'Bronze 8 mm ESG · 1 Teil', fase: 'ok', prazo: '8 T über', selo: 'überfällig', tom: 'atraso' },
      { n: '2600068', cliente: 'Talglas GmbH', vidro: 'Klar 4 mm Float · 1 Teil', fase: 'espera', prazo: 'kein Termin', selo: 'wartet auf Freigabe', tom: 'espera' },
    ],
  },
  producao: {
    modulo: 'Produktion',
    itens: ['Tafel', 'Fluss', 'Versand', 'Maschinen'],
    migalha: 'NeoGlass Produktion › Fluss',
    titulo: 'Produktionsfluss',
    subtitulo: 'Die Warteschlange jeder Maschine, in Stunden',
    unidade: 'Std. Warteschlange',
    gargalo: 'Engpass',
    folga: 'Mit Luft',
    maquinas: [
      { nome: 'Schneidtisch', fila: '6.4' },
      { nome: 'Schleifmaschine', fila: '2.1' },
      { nome: 'Waschmaschine', fila: '0.8' },
      { nome: 'Härteofen', fila: '3.2' },
    ],
    agora: { titulo: 'Was jetzt zu tun ist', rotulo: 'Engpass heute', maquina: 'Schneidtisch' },
    margem: { titulo: 'Terminpuffer', faixas: ['Im Takt', 'Achtung', 'Gerissen'] },
  },
  design: {
    modulo: 'Design',
    itens: ['Projekte', 'Bibliothek', '2D-Bild', 'Beschläge'],
    titulo: 'Öffnung testen',
    sub: 'Eckdusche · Schiebetür',
    dica: 'Ziehen, um die Kamera zu drehen',
    ferragens: 'Beschläge',
    cancelar: 'Abbrechen',
    abrir: 'Öffnen',
  },

  corte: {
    modulo: 'Optimierung',
    itens: ['Tafel', 'Optimierung', 'Reststücke', 'Maschinen'],
    migalha: 'NeoGlass Produktion › Optimierung',
    titulo: 'Schnittplan',
    subtitulo: 'Eine Tafel, der ganze Auftrag verschachtelt',
    chapa: 'Tafel',
    aproveitamento: 'Ausnutzung',
    legenda: ['Duschtür', 'Seitenteil', 'Regalboden', 'Spiegel'],
  },

  ia: {
    modulo: 'Künstliche Intelligenz',
    itens: ['Assistent', 'Prüfungen', 'Verlauf', 'Einstellungen'],
    migalha: 'NeoGlass › Assistent',
    titulo: 'Assistent',
    subtitulo: 'Fragen Sie nach der Scheibe',
    voce: 'Sie',
    pergunta: 'Wo ist VG-260918-03?',
    resposta: 'Schneidtisch. Geht morgen raus.',
  },

  automacao: {
    modulo: 'Automatisierung',
    itens: ['Warteschlangen', 'Regeln', 'Verlauf', 'Einstellungen'],
    migalha: 'NeoGlass › Warteschlangen',
    titulo: 'Lief von allein',
    subtitulo: 'Niemand hat geklickt',
    feitos: [
      { nome: 'Zahlschein gesendet', quando: '00:14' },
      { nome: 'Kunde benachrichtigt', quando: '00:14' },
      { nome: 'Bestand gebucht', quando: '00:15' },
    ],
  },

  visao: {
    modulo: 'Computer Vision',
    itens: ['Kamera', 'Öffnungen', 'Prüfung', 'Einstellungen'],
    migalha: 'NeoGlass › Kamera',
    titulo: 'Die Kamera hat gemessen',
    subtitulo: 'Öffnung · 1800 × 1100',
    medida: '1800 × 1100',
  },

  dados: {
    modulo: 'Daten',
    itens: ['Heute', 'Aufträge', 'Marge', 'Einstellungen'],
    migalha: 'NeoGlass › Heute',
    titulo: 'Heute in der Fabrik',
    subtitulo: 'Was schon passiert ist',
    numeros: [
      { n: '38', rotulo: 'im Plan' },
      { n: '2', rotulo: 'überfällig' },
      { n: '41,7%', rotulo: 'Marge' },
    ],
  },
}
