export default {
  endereco: 'app.neoglass.online',
  ferramentas: 'Herramientas',
  usuario: 'Tu nombre',
  papel: 'NeoGlass · Usuario',
  pedidos: {
    modulo: 'Pedidos',
    itens: ['Panel', 'Presupuestos', 'Pedidos', 'Reposición'],
    migalha: 'NeoGlass Pedidos › Panel',
    titulo: 'Pedidos',
    subtitulo: 'Todos los pedidos · plazos y fases',
    busca: 'Buscar por cliente, número de pedido…',
    filtro: 'En curso',
    fase: { ok: 'Autorizado', espera: 'No autorizado' },
    linhas: [
      { n: '2600073', cliente: 'Cristalería Central', vidro: 'Incoloro 6 mm templado · 6 piezas', fase: 'ok', prazo: 'en 9d', selo: 'a tiempo', tom: 'ok' },
      { n: '2600072', cliente: 'Obra Jardín Norte', vidro: 'Incoloro 6 mm templado · 4 piezas', fase: 'ok', prazo: 'en 1d', selo: 'urgente', tom: 'ok' },
      { n: '2600071', cliente: 'Constructora Aurora', vidro: 'Bronce 8 mm templado · 1 pieza', fase: 'ok', prazo: '8d de retraso', selo: 'vencido', tom: 'atraso' },
      { n: '2600068', cliente: 'Vidrios del Valle', vidro: 'Incoloro 4 mm común · 1 pieza', fase: 'espera', prazo: 'sin fecha', selo: 'espera aprobación', tom: 'espera' },
    ],
  },
  producao: {
    modulo: 'Producción',
    itens: ['Panel', 'Flujo', 'Expedición', 'Máquinas'],
    migalha: 'NeoGlass Producción › Flujo',
    titulo: 'Flujo de producción',
    subtitulo: 'La cola de cada máquina, en horas',
    unidade: 'h en cola',
    gargalo: 'Cuello de botella',
    folga: 'Con holgura',
    maquinas: [
      { nome: 'Mesa de corte', fila: '6.4' },
      { nome: 'Pulidora', fila: '2.1' },
      { nome: 'Lavadora', fila: '0.8' },
      { nome: 'Templado', fila: '3.2' },
    ],
    agora: { titulo: 'Qué hacer ahora', rotulo: 'Cuello de hoy', maquina: 'Mesa de corte' },
    margem: { titulo: 'Margen de plazo', faixas: ['A ritmo', 'Atención', 'Rebasado'] },
  },
  design: {
    modulo: 'Design',
    itens: ['Proyectos', 'Biblioteca', 'Imagen 2D', 'Herrajes'],
    titulo: 'Probar la apertura',
    sub: 'Mampara de esquina · corredera',
    dica: 'Arrastra para girar la cámara',
    ferragens: 'Herrajes',
    cancelar: 'Cancelar',
    abrir: 'Abrir',
  },

  corte: {
    modulo: 'Optimización',
    itens: ['Panel', 'Optimización', 'Retales', 'Máquinas'],
    migalha: 'NeoGlass Producción › Optimización',
    titulo: 'Plan de corte',
    subtitulo: 'Una plancha, el pedido entero encajado',
    chapa: 'Plancha',
    aproveitamento: 'de aprovechamiento',
    legenda: ['Puerta de mampara', 'Fijo lateral', 'Estante', 'Espejo'],
  },

  ia: {
    modulo: 'Inteligencia artificial',
    itens: ['Asistente', 'Revisiones', 'Historial', 'Ajustes'],
    migalha: 'NeoGlass › Asistente',
    titulo: 'Asistente',
    subtitulo: 'Pregunte por el vidrio',
    voce: 'Tú',
    pergunta: '¿Dónde está VG-260918-03?',
    resposta: 'Mesa de corte. Sale mañana.',
  },

  automacao: {
    modulo: 'Automatización',
    itens: ['Colas', 'Reglas', 'Historial', 'Ajustes'],
    migalha: 'NeoGlass › Colas',
    titulo: 'Corrió solo',
    subtitulo: 'Nadie hizo clic',
    feitos: [
      { nome: 'Boleto enviado', quando: '00:14' },
      { nome: 'Cliente avisado', quando: '00:14' },
      { nome: 'Stock descontado', quando: '00:15' },
    ],
  },

  visao: {
    modulo: 'Visión computacional',
    itens: ['Cámara', 'Huecos', 'Revisión', 'Ajustes'],
    migalha: 'NeoGlass › Cámara',
    titulo: 'La cámara midió',
    subtitulo: 'Hueco · 1800 × 1100',
    medida: '1800 × 1100',
  },

  dados: {
    modulo: 'Datos',
    itens: ['Hoy', 'Pedidos', 'Margen', 'Ajustes'],
    migalha: 'NeoGlass › Hoy',
    titulo: 'Hoy en la fábrica',
    subtitulo: 'Lo que ya pasó',
    numeros: [
      { n: '38', rotulo: 'a tiempo' },
      { n: '2', rotulo: 'atrasadas' },
      { n: '41,7%', rotulo: 'margen' },
    ],
  },
}
