/**
 * A página /tempera: a calculadora da têmpera, destino do filme e do anúncio.
 *
 * Sete perguntas, uma por tela. O preço em reais só aparece em português: a
 * tabela é brasileira, e converter para franco ou euro seria fingir uma
 * proposta que ninguém fez. Nos outros idiomas a faixa aparece e o valor fica
 * para a conversa.
 */
export default {
  pt: {
    seo: { nome: 'Têmpera', titulo: 'Quanto custa o NeoGlass na sua têmpera · em 30 segundos', descricao: 'Sete perguntas e você vê a mensalidade pela sua produção, como os dados chegam, como testar e quando começar. Sem cadastro.', ogTitulo: 'Quanto custa o NeoGlass na sua têmpera?', ogDescricao: 'Preço pela produção, dados, testes e início. Em 30 segundos, sem cadastro.' },
    etapas: ['Negócio', 'Produção', 'Dados', 'Testes', 'Início', 'Conversa', 'Contato'],
    mensal: 'Mensal', unica: 'Uma vez', unicaDiarias: 'Uma vez + diárias', concluido: 'Concluído', naConversa: 'na conversa',
    continuar: 'Continuar', voltar: '← Voltar', enviar: 'Enviar', enviando: 'Enviando…', gratis: 'grátis', incluso: 'incluso', recomendado: 'recomendado', porDia: '/dia',
    neg: { rot: 'Para começar', titulo: ['O seu negócio é uma', 'têmpera ou uma vidraçaria?'], texto: 'Em 30 segundos você vê o preço e como seria começar. Sem cadastro.',
      tempera: ['Têmpera de vidro', 'Indústria: corte, lapidação, furação, forno.'], vidracaria: ['Vidraçaria', 'Orçamento, projeto, venda e instalação.'] },
    vid: { rot: 'Vidraçaria', titulo: ['Para vidraçaria,', 'você mesmo começa.'], texto: (preco) => `Crie a conta e use na hora: 14 dias grátis, sem cartão. Depois, ${preco} por mês.`, acao: 'Criar a conta da vidraçaria' },
    prod: { rot: 'Produção', titulo: ['Quanto vidro passa pela sua têmpera', 'por mês?'], min: '1 mil m²', max: '15 mil m²+', ate: 'até', a: 'a', porMes: 'por mês', sobConsulta: 'Sob consulta',
      dentro: 'Qualquer produção dentro dessa faixa paga o mesmo. Usuários ilimitados.', acima: 'Acima de 15 mil m² a gente monta a proposta com você na conversa.', semPreco: '', faixa: (a, b) => `${a} a ${b} m²`, ateFaixa: (b) => `até ${b} m²`, maisDe: (a) => `mais de ${a} m²` },
    dad: { rot: 'Seus dados', titulo: ['Como você quer trazer os seus dados', 'para o NeoGlass?'], texto: 'Clientes, matéria-prima, tabela de preços e máquinas.',
      sozinho: ['Eu migro, aos poucos', 'Com as planilhas modelo e o guia da NeoGlass, no ritmo da sua equipe.'], neoglass: ['A NeoGlass migra para mim', 'A gente tira do seu sistema atual ou das planilhas e coloca no NeoGlass. Você só confere.'] },
    teste: { rot: 'Testes', titulo: ['Como você quer', 'testar o sistema?'], texto: 'A gente acompanha os primeiros pedidos com a sua equipe.',
      remoto: ['Remoto', 'Por vídeo, no horário da sua equipe.'], presencial: ['Presencial', 'Alguém da NeoGlass na sua fábrica. Hotel e transporte por conta da sua empresa; os dias a gente combina na conversa.'] },
    ini: { rot: 'Início', titulo: ['Quando você quer', 'começar a usar?'], ja: 'O quanto antes', mes: 'No próximo mês', depois: 'Daqui a 2 ou 3 meses' },
    quem: { rot: 'Conversa', titulo: ['Uma conversa de 20 a 30 minutos.', 'Quem participa?'], texto: 'Online, para entender a sua fábrica e confirmar tudo o que você escolheu.',
      dono: ['O proprietário', 'Eu mesmo.'], enc: ['O encarregado', 'Quem cuida da produção, gerente ou PCP.'], ambos: ['Os dois', 'Quem decide e quem opera na mesma conversa.'] },
    contato: { rot: 'Contato', titulo: ['Pronto.', 'Para onde a gente manda?'], texto: 'A gente chama no WhatsApp para marcar o melhor horário.',
      nome: 'Seu nome', empresa: 'Empresa', whatsapp: 'WhatsApp', encarregado: 'Encarregado', encNome: 'Nome', placeholder: '(00) 00000-0000',
      falta: { nome: 'Falta o nome.', empresa: 'Falta a empresa.', whatsapp: 'Falta o WhatsApp.' }, erro: 'Não deu para enviar agora. Abrimos o WhatsApp com tudo preenchido para você mandar direto.', muitas: 'Muitas tentativas seguidas. Espere alguns minutos e tente de novo.' },
    feito: { titulo: (nome) => ['Recebido,', `${nome}.`], texto: (enc) => `A gente chama ${enc ? `você e ${enc}` : 'você'} no WhatsApp para marcar a conversa. Até lá, nada a pagar e nada a instalar.`,
      producao: 'Produção', mensalidade: 'Mensalidade', dados: 'Dados', testes: 'Testes', comecar: 'Começar', conversa: 'Conversa com',
      dadosV: { sozinho: 'Eu migro · grátis', neoglass: (v) => `NeoGlass migra · ${v}` }, testesV: { remoto: 'Remoto · incluso', presencial: (v) => `Presencial · ${v}/dia` },
      quemV: { dono: 'O proprietário', enc: 'O encarregado', ambos: 'Proprietário e encarregado' } },
    whatsapp: (r) => `Olá, Higor! Vim pela página da têmpera.\n\nEmpresa: ${r.empresa}\nNome: ${r.nome}\nProdução: ${r.faixa}\nDados: ${r.dados}\nTestes: ${r.testes}\nComeçar: ${r.inicio}\nConversa com: ${r.quem}`,
  },
  en: {
    seo: { nome: 'Tempering', titulo: 'What NeoGlass costs for your tempering plant · in 30 seconds', descricao: 'Seven questions and you see how we price by production, how your data comes in, how to test and when to start. No sign-up.', ogTitulo: 'What would NeoGlass cost your tempering plant?', ogDescricao: 'Production band, data, testing and start date. In 30 seconds, no sign-up.' },
    etapas: ['Business', 'Production', 'Data', 'Testing', 'Start', 'Call', 'Contact'],
    mensal: 'Monthly', unica: 'One-off', unicaDiarias: 'One-off + daily rate', concluido: 'Done', naConversa: 'on the call',
    continuar: 'Continue', voltar: '← Back', enviar: 'Send', enviando: 'Sending…', gratis: 'free', incluso: 'included', recomendado: 'recommended', porDia: '/day',
    neg: { rot: 'To start', titulo: ['Is your business a', 'tempering plant or a glazier?'], texto: 'In 30 seconds you see how it works and what starting looks like. No sign-up.',
      tempera: ['Glass tempering plant', 'Industry: cutting, edging, drilling, furnace.'], vidracaria: ['Glazier', 'Quotes, projects, sales and installation.'] },
    vid: { rot: 'Glazier', titulo: ['For glaziers,', 'you start on your own.'], texto: (preco) => `Create the account and use it right away: 14 days free, no card. Then ${preco} a month.`, acao: 'Create the glazier account' },
    prod: { rot: 'Production', titulo: ['How much glass goes through your plant', 'each month?'], min: '1k m²', max: '15k m²+', ate: 'up to', a: 'to', porMes: 'per month', sobConsulta: 'On request',
      dentro: 'Any production inside this band pays the same. Unlimited users.', acima: 'Above 15,000 m² we build the proposal with you on the call.', semPreco: 'The price in your currency comes in the proposal after the call.', faixa: (a, b) => `${a} to ${b} m²`, ateFaixa: (b) => `up to ${b} m²`, maisDe: (a) => `over ${a} m²` },
    dad: { rot: 'Your data', titulo: ['How do you want to bring your data', 'into NeoGlass?'], texto: 'Customers, raw material, price list and machines.',
      sozinho: ['I migrate, step by step', 'With the NeoGlass template sheets and guide, at your team’s pace.'], neoglass: ['NeoGlass migrates for me', 'We take it from your current system or spreadsheets and load it into NeoGlass. You just check.'] },
    teste: { rot: 'Testing', titulo: ['How do you want to', 'test the system?'], texto: 'We follow the first orders with your team.',
      remoto: ['Remote', 'By video call, on your team’s schedule.'], presencial: ['On site', 'Someone from NeoGlass at your plant. Hotel and travel paid by your company; we agree the days on the call.'] },
    ini: { rot: 'Start', titulo: ['When do you want to', 'start using it?'], ja: 'As soon as possible', mes: 'Next month', depois: 'In 2 or 3 months' },
    quem: { rot: 'Call', titulo: ['A 20 to 30 minute call.', 'Who joins?'], texto: 'Online, to understand your plant and confirm everything you chose.',
      dono: ['The owner', 'Myself.'], enc: ['The supervisor', 'Who runs production, manager or planning.'], ambos: ['Both', 'Who decides and who operates, in the same call.'] },
    contato: { rot: 'Contact', titulo: ['Done.', 'Where do we reach you?'], texto: 'We message you on WhatsApp to book the best time.',
      nome: 'Your name', empresa: 'Company', whatsapp: 'WhatsApp', encarregado: 'Supervisor', encNome: 'Name', placeholder: '+00 00 000 00 00',
      falta: { nome: 'Your name is missing.', empresa: 'The company is missing.', whatsapp: 'WhatsApp is missing.' }, erro: 'We could not send it right now. We opened WhatsApp with everything filled in so you can send it directly.', muitas: 'Too many attempts in a row. Wait a few minutes and try again.' },
    feito: { titulo: (nome) => ['Received,', `${nome}.`], texto: (enc) => `We will message ${enc ? `you and ${enc}` : 'you'} on WhatsApp to book the call. Until then, nothing to pay and nothing to install.`,
      producao: 'Production', mensalidade: 'Monthly fee', dados: 'Data', testes: 'Testing', comecar: 'Start', conversa: 'Call with',
      dadosV: { sozinho: 'I migrate · free', neoglass: (v) => `NeoGlass migrates · ${v}` }, testesV: { remoto: 'Remote · included', presencial: (v) => `On site · ${v}/day` },
      quemV: { dono: 'The owner', enc: 'The supervisor', ambos: 'Owner and supervisor' } },
    whatsapp: (r) => `Hello Higor! I came from the tempering page.\n\nCompany: ${r.empresa}\nName: ${r.nome}\nProduction: ${r.faixa}\nData: ${r.dados}\nTesting: ${r.testes}\nStart: ${r.inicio}\nCall with: ${r.quem}`,
  },
  es: {
    seo: { nome: 'Templado', titulo: 'Cuánto cuesta NeoGlass en su templadora · en 30 segundos', descricao: 'Siete preguntas y ve cómo cobramos por producción, cómo llegan sus datos, cómo probar y cuándo empezar. Sin registro.', ogTitulo: '¿Cuánto costaría NeoGlass en su templadora?', ogDescricao: 'Franja de producción, datos, pruebas e inicio. En 30 segundos, sin registro.' },
    etapas: ['Negocio', 'Producción', 'Datos', 'Pruebas', 'Inicio', 'Charla', 'Contacto'],
    mensal: 'Mensual', unica: 'Una vez', unicaDiarias: 'Una vez + jornadas', concluido: 'Listo', naConversa: 'en la charla',
    continuar: 'Continuar', voltar: '← Volver', enviar: 'Enviar', enviando: 'Enviando…', gratis: 'gratis', incluso: 'incluido', recomendado: 'recomendado', porDia: '/día',
    neg: { rot: 'Para empezar', titulo: ['¿Su negocio es una', 'templadora o una cristalería?'], texto: 'En 30 segundos ve cómo funciona y cómo sería empezar. Sin registro.',
      tempera: ['Templadora de vidrio', 'Industria: corte, canteado, taladrado, horno.'], vidracaria: ['Cristalería', 'Presupuestos, proyectos, venta e instalación.'] },
    vid: { rot: 'Cristalería', titulo: ['Para cristalerías,', 'usted mismo empieza.'], texto: (preco) => `Cree la cuenta y úsela ya: 14 días gratis, sin tarjeta. Después, ${preco} al mes.`, acao: 'Crear la cuenta de la cristalería' },
    prod: { rot: 'Producción', titulo: ['¿Cuánto vidrio pasa por su templadora', 'al mes?'], min: '1 mil m²', max: '15 mil m²+', ate: 'hasta', a: 'a', porMes: 'al mes', sobConsulta: 'A consultar',
      dentro: 'Cualquier producción dentro de esta franja paga lo mismo. Usuarios ilimitados.', acima: 'Por encima de 15 mil m² armamos la propuesta con usted en la charla.', semPreco: 'El precio en su moneda llega en la propuesta, después de la charla.', faixa: (a, b) => `${a} a ${b} m²`, ateFaixa: (b) => `hasta ${b} m²`, maisDe: (a) => `más de ${a} m²` },
    dad: { rot: 'Sus datos', titulo: ['¿Cómo quiere traer sus datos', 'a NeoGlass?'], texto: 'Clientes, materia prima, lista de precios y máquinas.',
      sozinho: ['Migro yo, de a poco', 'Con las planillas modelo y la guía de NeoGlass, al ritmo de su equipo.'], neoglass: ['NeoGlass migra por mí', 'Los sacamos de su sistema actual o de las planillas y los cargamos en NeoGlass. Usted solo revisa.'] },
    teste: { rot: 'Pruebas', titulo: ['¿Cómo quiere', 'probar el sistema?'], texto: 'Acompañamos los primeros pedidos con su equipo.',
      remoto: ['Remoto', 'Por videollamada, en el horario de su equipo.'], presencial: ['Presencial', 'Alguien de NeoGlass en su fábrica. Hotel y transporte a cargo de su empresa; los días los acordamos en la charla.'] },
    ini: { rot: 'Inicio', titulo: ['¿Cuándo quiere', 'empezar a usarlo?'], ja: 'Lo antes posible', mes: 'El mes que viene', depois: 'En 2 o 3 meses' },
    quem: { rot: 'Charla', titulo: ['Una charla de 20 a 30 minutos.', '¿Quién participa?'], texto: 'En línea, para entender su fábrica y confirmar todo lo que eligió.',
      dono: ['El propietario', 'Yo mismo.'], enc: ['El encargado', 'Quien lleva la producción, gerente o planificación.'], ambos: ['Los dos', 'Quien decide y quien opera, en la misma charla.'] },
    contato: { rot: 'Contacto', titulo: ['Listo.', '¿Adónde le escribimos?'], texto: 'Le escribimos por WhatsApp para fijar el mejor horario.',
      nome: 'Su nombre', empresa: 'Empresa', whatsapp: 'WhatsApp', encarregado: 'Encargado', encNome: 'Nombre', placeholder: '+00 000 000 000',
      falta: { nome: 'Falta el nombre.', empresa: 'Falta la empresa.', whatsapp: 'Falta el WhatsApp.' }, erro: 'No pudimos enviarlo ahora. Abrimos WhatsApp con todo completado para que lo mande directo.', muitas: 'Demasiados intentos seguidos. Espere unos minutos y vuelva a intentar.' },
    feito: { titulo: (nome) => ['Recibido,', `${nome}.`], texto: (enc) => `Le escribimos${enc ? ` a usted y a ${enc}` : ''} por WhatsApp para fijar la charla. Hasta entonces, nada que pagar ni que instalar.`,
      producao: 'Producción', mensalidade: 'Mensualidad', dados: 'Datos', testes: 'Pruebas', comecar: 'Empezar', conversa: 'Charla con',
      dadosV: { sozinho: 'Migro yo · gratis', neoglass: (v) => `NeoGlass migra · ${v}` }, testesV: { remoto: 'Remoto · incluido', presencial: (v) => `Presencial · ${v}/día` },
      quemV: { dono: 'El propietario', enc: 'El encargado', ambos: 'Propietario y encargado' } },
    whatsapp: (r) => `¡Hola, Higor! Vengo de la página de templado.\n\nEmpresa: ${r.empresa}\nNombre: ${r.nome}\nProducción: ${r.faixa}\nDatos: ${r.dados}\nPruebas: ${r.testes}\nEmpezar: ${r.inicio}\nCharla con: ${r.quem}`,
  },
  de: {
    seo: { nome: 'Vorspannung', titulo: 'Was NeoGlass in Ihrer Vorspannerei kostet · in 30 Sekunden', descricao: 'Sieben Fragen, und Sie sehen, wie wir nach Produktion abrechnen, wie Ihre Daten kommen, wie Sie testen und wann Sie starten. Ohne Registrierung.', ogTitulo: 'Was würde NeoGlass in Ihrer Vorspannerei kosten?', ogDescricao: 'Produktionsstufe, Daten, Tests und Start. In 30 Sekunden, ohne Registrierung.' },
    etapas: ['Betrieb', 'Produktion', 'Daten', 'Tests', 'Start', 'Gespräch', 'Kontakt'],
    mensal: 'Monatlich', unica: 'Einmalig', unicaDiarias: 'Einmalig + Tagessätze', concluido: 'Erledigt', naConversa: 'im Gespräch',
    continuar: 'Weiter', voltar: '← Zurück', enviar: 'Senden', enviando: 'Wird gesendet…', gratis: 'gratis', incluso: 'inklusive', recomendado: 'empfohlen', porDia: '/Tag',
    neg: { rot: 'Zum Start', titulo: ['Ist Ihr Betrieb eine', 'Vorspannerei oder eine Glaserei?'], texto: 'In 30 Sekunden sehen Sie, wie es funktioniert und wie der Start aussieht. Ohne Registrierung.',
      tempera: ['Glasvorspannerei', 'Industrie: Zuschnitt, Kantenbearbeitung, Bohren, Ofen.'], vidracaria: ['Glaserei', 'Offerten, Projekte, Verkauf und Montage.'] },
    vid: { rot: 'Glaserei', titulo: ['Für Glasereien:', 'Sie starten selbst.'], texto: (preco) => `Konto erstellen und sofort nutzen: 14 Tage gratis, ohne Karte. Danach ${preco} pro Monat.`, acao: 'Glaserei-Konto erstellen' },
    prod: { rot: 'Produktion', titulo: ['Wie viel Glas geht durch Ihre Vorspannerei', 'pro Monat?'], min: '1000 m²', max: '15 000 m²+', ate: 'bis', a: 'bis', porMes: 'pro Monat', sobConsulta: 'Auf Anfrage',
      dentro: 'Jede Produktion innerhalb dieser Stufe zahlt gleich viel. Unbegrenzte Benutzer.', acima: 'Über 15 000 m² erstellen wir das Angebot mit Ihnen im Gespräch.', semPreco: 'Den Preis in Ihrer Währung erhalten Sie nach dem Gespräch mit der Offerte.', faixa: (a, b) => `${a} bis ${b} m²`, ateFaixa: (b) => `bis ${b} m²`, maisDe: (a) => `über ${a} m²` },
    dad: { rot: 'Ihre Daten', titulo: ['Wie sollen Ihre Daten', 'zu NeoGlass kommen?'], texto: 'Kunden, Rohmaterial, Preisliste und Maschinen.',
      sozinho: ['Ich migriere schrittweise', 'Mit den Vorlagen und der Anleitung von NeoGlass, im Tempo Ihres Teams.'], neoglass: ['NeoGlass migriert für mich', 'Wir holen sie aus Ihrem System oder Ihren Tabellen und laden sie in NeoGlass. Sie prüfen nur.'] },
    teste: { rot: 'Tests', titulo: ['Wie möchten Sie', 'das System testen?'], texto: 'Wir begleiten die ersten Aufträge mit Ihrem Team.',
      remoto: ['Remote', 'Per Videocall, zu den Zeiten Ihres Teams.'], presencial: ['Vor Ort', 'Jemand von NeoGlass in Ihrem Werk. Hotel und Reise übernimmt Ihr Betrieb; die Tage vereinbaren wir im Gespräch.'] },
    ini: { rot: 'Start', titulo: ['Wann möchten Sie', 'starten?'], ja: 'So bald wie möglich', mes: 'Nächsten Monat', depois: 'In 2 oder 3 Monaten' },
    quem: { rot: 'Gespräch', titulo: ['Ein Gespräch von 20 bis 30 Minuten.', 'Wer nimmt teil?'], texto: 'Online, um Ihr Werk zu verstehen und Ihre Auswahl zu bestätigen.',
      dono: ['Der Inhaber', 'Ich selbst.'], enc: ['Der Vorarbeiter', 'Wer die Produktion führt, Leitung oder Planung.'], ambos: ['Beide', 'Wer entscheidet und wer bedient, im selben Gespräch.'] },
    contato: { rot: 'Kontakt', titulo: ['Fertig.', 'Wo erreichen wir Sie?'], texto: 'Wir melden uns per WhatsApp, um den besten Termin zu finden.',
      nome: 'Ihr Name', empresa: 'Firma', whatsapp: 'WhatsApp', encarregado: 'Vorarbeiter', encNome: 'Name', placeholder: '+41 00 000 00 00',
      falta: { nome: 'Der Name fehlt.', empresa: 'Die Firma fehlt.', whatsapp: 'WhatsApp fehlt.' }, erro: 'Das Senden hat gerade nicht geklappt. Wir haben WhatsApp mit allen Angaben geöffnet, damit Sie es direkt senden können.', muitas: 'Zu viele Versuche hintereinander. Bitte warten Sie einige Minuten.' },
    feito: { titulo: (nome) => ['Erhalten,', `${nome}.`], texto: (enc) => `Wir melden uns per WhatsApp bei ${enc ? `Ihnen und ${enc}` : 'Ihnen'}, um das Gespräch zu vereinbaren. Bis dahin nichts zu bezahlen und nichts zu installieren.`,
      producao: 'Produktion', mensalidade: 'Monatlich', dados: 'Daten', testes: 'Tests', comecar: 'Start', conversa: 'Gespräch mit',
      dadosV: { sozinho: 'Ich migriere · gratis', neoglass: (v) => `NeoGlass migriert · ${v}` }, testesV: { remoto: 'Remote · inklusive', presencial: (v) => `Vor Ort · ${v}/Tag` },
      quemV: { dono: 'Der Inhaber', enc: 'Der Vorarbeiter', ambos: 'Inhaber und Vorarbeiter' } },
    whatsapp: (r) => `Hallo Higor! Ich komme von der Seite zur Vorspannerei.\n\nFirma: ${r.empresa}\nName: ${r.nome}\nProduktion: ${r.faixa}\nDaten: ${r.dados}\nTests: ${r.testes}\nStart: ${r.inicio}\nGespräch mit: ${r.quem}`,
  },
}
